name: CD

on:
    push:
        branches:
            - main

jobs:
    lint:
        uses: ./.github/workflows/job-template.yml
        with:
            commands: npm run lint

    test:
        uses: ./.github/workflows/job-template.yml
        with:
            commands: npm run test

    check:
        uses: ./.github/workflows/job-template.yml
        with:
            commands: npm run check

    deploy:
        needs: [lint, test, check]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci && npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SVEV_DEV }}
                  channelId: live
                  projectId: svev-dev
