name: CI

on:
    pull_request:

jobs:
    lint:
        uses: ./.github/workflows/job-template.yml
        with:
            commands: npm run lint

    test:
        uses: ./.github/workflows/job-template.yml
        with:
            commands: npm run test

    check:
        uses: ./.github/workflows/job-template.yml
        with:
            commands: npm run check

    build:
        uses: ./.github/workflows/job-template.yml
        with:
            commands: npm run build
