name: Job Template

on:
    workflow_call:
        inputs:
            commands:
                required: true
                type: string
                description: 'The commands to run (can be multiple lines)'

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: 'npm'
            - run: npm ci
            - run: |
                ${{ inputs.commands }} 